//! PROV-DM-inspired causal graph types.
//! Maps AEP actions onto Activity/Entity/Agent triples for causal traversal.

use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvActivity {
    pub id: String,
    pub label: String,
    pub used: Vec<String>,
    pub generated: Vec<String>,
    pub timestamp_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvEntity {
    pub id: String,
    pub digest: Option<String>,
    pub generated_by: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvAgent {
    pub id: String,
    pub label: String,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct ProvGraph {
    pub activities: HashMap<String, ProvActivity>,
    pub entities: HashMap<String, ProvEntity>,
    pub agents: HashMap<String, ProvAgent>,
}

impl ProvGraph {
    /// Return the IDs of activities that transitively produced `entity_id`
    /// (walking `generated_by` → `used` edges upstream).
    ///
    /// Each activity appears at most once in the result. Graphs provided by
    /// evidence producers are untrusted input, so cycles are handled by
    /// construction: a visited-set terminates traversal instead of looping.
    pub fn ancestors(&self, entity_id: &str) -> Vec<String> {
        let mut ancestors = Vec::new();
        let mut seen_activities: HashSet<&str> = HashSet::new();
        let mut seen_entities: HashSet<&str> = HashSet::new();
        let mut stack = vec![entity_id];
        seen_entities.insert(entity_id);
        while let Some(eid) = stack.pop() {
            let Some(entity) = self.entities.get(eid) else {
                continue;
            };
            let Some(act_id) = entity.generated_by.as_deref() else {
                continue;
            };
            if !seen_activities.insert(act_id) {
                continue;
            }
            ancestors.push(act_id.to_string());
            if let Some(activity) = self.activities.get(act_id) {
                for used in &activity.used {
                    if seen_entities.insert(used.as_str()) {
                        stack.push(used.as_str());
                    }
                }
            }
        }
        ancestors
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn activity(id: &str, used: &[&str]) -> ProvActivity {
        ProvActivity {
            id: id.into(),
            label: id.into(),
            used: used.iter().map(|s| s.to_string()).collect(),
            generated: vec![],
            timestamp_ms: 0,
        }
    }

    fn entity(id: &str, generated_by: Option<&str>) -> ProvEntity {
        ProvEntity {
            id: id.into(),
            digest: None,
            generated_by: generated_by.map(|s| s.to_string()),
        }
    }

    fn graph(activities: &[ProvActivity], entities: &[ProvEntity]) -> ProvGraph {
        let mut g = ProvGraph::default();
        for a in activities {
            g.activities.insert(a.id.clone(), a.clone());
        }
        for e in entities {
            g.entities.insert(e.id.clone(), e.clone());
        }
        g
    }

    #[test]
    fn ancestors_walks_generated_by_then_used_chain() {
        // input(entity, by=act1) ← used ← output(entity, by=act2)
        let g = graph(
            &[activity("act1", &["output"]), activity("act2", &[])],
            &[
                entity("input", Some("act1")),
                entity("output", Some("act2")),
            ],
        );
        assert_eq!(
            g.ancestors("input"),
            vec!["act1".to_string(), "act2".to_string()]
        );
    }

    #[test]
    fn ancestors_returns_empty_for_unknown_or_root_entity() {
        let g = graph(&[activity("act1", &[])], &[entity("root", None)]);
        assert!(g.ancestors("missing").is_empty());
        assert!(g.ancestors("root").is_empty());
    }

    #[test]
    fn ancestors_deduplicates_shared_activities() {
        // Two inputs both generated by act1, which used a shared intermediate.
        let g = graph(
            &[activity("act1", &["mid"])],
            &[
                entity("in-a", Some("act1")),
                entity("in-b", Some("act1")),
                entity("mid", None),
            ],
        );
        assert_eq!(g.ancestors("in-a"), vec!["act1".to_string()]);
        assert_eq!(g.ancestors("in-b"), vec!["act1".to_string()]);
    }

    #[test]
    fn ancestors_terminates_on_cyclic_graph() {
        // act1 uses "out", generated by act2, which uses "in", generated by
        // act1 again — a cycle must terminate, not loop forever.
        let g = graph(
            &[activity("act1", &["out"]), activity("act2", &["in"])],
            &[entity("in", Some("act1")), entity("out", Some("act2"))],
        );
        let result = g.ancestors("in");
        assert_eq!(result.len(), 2);
        let mut sorted = result.clone();
        sorted.sort();
        assert_eq!(sorted, vec!["act1".to_string(), "act2".to_string()]);
    }
}
